version: '3.3'

services:

  back:
    build: ./back
    stdin_open: true
    tty: true
    expose:
      - "3000"
    networks:
      - app-network

  front:
    build: ./front
    stdin_open: true
    tty: true
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

  mysql:
    image: mysql:8.2.0
    stdin_open: true
    tty: true
    environment:
      - MYSQL_DATABASE=platinum
      - MYSQL_USER=iplat_111
      - MYSQL_PASSWORD=alistan1066
      - MYSQL_ROOT_PASSWORD=alistan1066
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
